#define SFX_CANCEL	0
#define SFX_CONFIRM	1
#define SFX_DRUMROLL	2
#define MOD_GAME_LOSE	0
#define MOD_GAME_WIN	1
#define SFX_MOVE	5
#define SFX_SELECT	6
#define SFX_SIMU_LOSE	7
#define SFX_SIMU_WIN	8
#define MSL_NSONGS	2
#define MSL_NSAMPS	9
#define MSL_BANKSIZE	11
